blocks:
  axe-blocks:
    - LOG
    - LOG_2
    - WOOD
    - WOOD_STEP
    - WOOD_DOUBLE_STEP
    - WOOD_STAIRS
    - BIRCH_WOOD_STAIRS
    - JUNGLE_WOOD_STAIRS
    - SPRUCE_WOOD_STAIRS
    - ACACIA_STAIRS
    - DARK_OAK_STAIRS
    - WORKBENCH
    - LADDER
    - RAILS
    - ACTIVATOR_RAIL
    - DETECTOR_RAIL
    - POWERED_RAIL
    - SIGN
    - SIGN_POST
    - PUMPKIN
    - JACK_O_LANTERN
    - HUGE_MUSHROOM_1
    - HUGE_MUSHROOM_2
    - FENCE
    - FENCE_GATE
  pickaxe-blocks:
    - STONE
    - GRANITE
    - POLISHED_GRANITE
    - DIORITE
    - POLISHED_DIORITE
    - ANDESITE
    - POLISHED_ANDESITE
    - INFESTED_STONE
    - INFESTED_COBBLESTONE
    - INFESTED_STONE_BRICKS
    - INFESTED_MOSSY_STONE_BRICKS
    - INFESTED_CRACKED_STONE_BRICKS
    - INFESTED_CHISELED_STONE_BRICKS
    - STONE_BRICKS
    - MOSSY_STONE_BRICKS
    - CRACKED_STONE_BRICKS
    - CHISELED_STONE_BRICKS
    - COBBLESTONE
    - MOSSY_COBBLESTONE
    - SANDSTONE
    - CHISELED_SANDSTONE
    - CUT_SANDSTONE
    - OBSIDIAN
    - IRON_BLOCK
    - LAPIS_BLOCK
    - GILDED_BLACKSTONE
    - GOLD_BLOCK
    - REDSTONE_BLOCK
    - EMERALD_BLOCK
    - DIAMOND_BLOCK
    - STEP
    - DOUBLE_STEP
    - COBBLESTONE_STAIRS
    - COBBLE_WALL
    - BRICK
    - BRICK_STAIRS
    - ICE
    - PACKED_ICE
    - NETHERRACK
    - NETHER_BRICK
    - NETHER_BRICK_STAIRS
    - NETHER_FENCE
    - QUARTZ_BLOCK
    - QUARTZ_STAIRS
    - CRIMSON_NYLIUM
    - WARPED_NYLIUM
    - BASALT
    - POLISHED_BASALT
    - BLACKSTONE
    - POLISHED_BLACKSTONE
    - CHISELED_POLISHED_BLACKSTONE
    - POLISHED_BLACKSTONE_BRICKS
    - CRACKED_POLISHED_BLACKSTONE_BRICKS
    - CLAY_BRICK
    - STAINED_CLAY
    - HARD_CLAY
    - WHITE_TERRACOTTA
    - ORANGE_TERRACOTTA
    - MAGENTA_TERRACOTTA
    - LIGHT_BLUE_TERRACOTTA
    - YELLOW_TERRACOTTA
    - LIME_TERRACOTTA
    - PINK_TERRACOTTA
    - GRAY_TERRACOTTA
    - LIGHT_GRAY_TERRACOTTA
    - CYAN_TERRACOTTA
    - PURPLE_TERRACOTTA
    - BLUE_TERRACOTTA
    - BROWN_TERRACOTTA
    - GREEN_TERRACOTTA
    - RED_TERRACOTTA
    - BLACK_TERRACOTTA
    - TERRACOTTA
  shear-blocks:
    - WOOL
    - LEAVES
    - LEAVES_2
  shovel-blocks:
    - GRASS
    - DIRT
    - SAND
    - GRAVEL
    - SNOW
    - SNOW_BLOCK
    - CLAY
    - SOUL_SAND
    - MYCEL
  sword-blocks:
    - MELON_BLOCK
    - WEB